//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public int BookId { get; set; }
        public string BookTitle { get; set; }
        public int BookAuthorId { get; set; }
        public Nullable<int> BookHolderId { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual User User { get; set; }
    }
}
